function prob = cond_slide(prob,data,bif_ind)
%COND_SLIDE Add an extra zero function to the COCO compatible problem for 
% following sliding bifurcations
% Input:
%   prob: COCO compatible problem structure generated by pwsdde_coco_prob.m
%   data: collocation data structure
%   bif_ind: index of grazing bifurcation in the solution signature
% Output:
%   prob: COCO compatible continuation problem structure with extra zero
%       function for a sliding event

uidx = prob.efunc.x_idx;
prob = coco_add_func(prob, 'slide_cond', ...
    @(p,d,u) pwsdde_slide(p,d,u,bif_ind), data, 'zero',...
    'uidx', uidx, 'F+DF');

end